[package]
name = "day10"
version = "0.1.0"
authors = ["James Humphries <jhumphries@vqcomms.com>"]
edition = "2018"

[unstable]
array_windows = 'yes'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
